language: python

python:
  - "2.7"

# command to install dependencies
install:
  - "pip install -r requirements.txt"

# command to run tests
script:
  # ensure README.md changes all synced to about.html
  - ./scripts/readme_to_about && git diff --exit-code
  - python manage.py test home
  - flake8 --ignore=E501 --exclude=migrations,wsgi.py
