 version: '2'
 services:
   db:
     image: postgres
     command: ["postgres", "-c", "log_statement=all"]
     ports:
       - 5432:5432
     environment:
       - POSTGRES_USER=sasha
       - POSTGRES_PASSWORD=sasha
       - POSTGRES_DB=blaggregator_dev
